### ISSUE TITLE
alexanderkoller /pocketsphinx / sphinx

### ISSUE THREAD

**Issue by KenyaLS** [alexanderkoller/jep-dialogos#2]
alexanderkoller /pocketsphinx / sphinx  
Do you still program voice to text? Or already without changes

**Comment by alexanderkoller** [comment]
We use Sphinx to do the speech recognition in DialogOS. Please see the [DialogOS website](https://www.dialogos.app/) for more details, and feel free to open another issue if you run into a technical problem.
