### ISSUE TITLE
Я Никита Краснов требую передать мне права на проект и все проекты связные с sphinx и pocketsphinx "Transfer ownership Transfer this repository to another user or to an organization where you have the ability to create repositories."

### ISSUE THREAD

**Issue by KenyaLS** [alexanderkoller/jep-dialogos#3]
Я Никита Краснов требую передать мне права на проект и все проекты связные с sphinx и pocketsphinx "Transfer ownership Transfer this repository to another user or to an organization where you have the ability to create repositories."
Надеюсь в фотографиях не нуждаюсь о подтверждении личности.
ГК РФ Статья 1255. Авторские права
 
1. Интеллектуальные права на произведения науки, литературы и искусства являются авторскими правами.
2. Автору произведения принадлежат следующие права:
1) исключительное право на произведение;
2) право авторства;
3) право автора на имя;
4) право на неприкосновенность произведения;
5) право на обнародование произведения.
3. В случаях, предусмотренных настоящим Кодексом, автору произведения наряду с правами, указанными в пункте 2 настоящей статьи, принадлежат другие права, в том числе право на вознаграждение за служебное произведение, право на отзыв, право следования, право доступа к произведениям изобразительного искусства.
(в ред. Федерального закона от 12.03.2014 N 35-ФЗ)
(см. текст в предыдущей редакции)

**Comment by alexanderkoller** [comment]
This looks like spam, closing the issue.
